version: '3'
services:
  api:
    build:
      context: .
    # container_name: url-shortner-api
    ports:
      - 3000:3000
    # deploy:
    #   mode: replicated
    #   replicas: 5
    
    # waiting for the deployment of the db
    depends_on:
      - mongo

    # loading envs from .env
    env_file:
      - .env
    
  mongo:
    image: mongo
    # container_name: url-shortner-db

    volumes:
      - "./mongodb:/data/db"
